{% set name = "snowflake-connector-python" %}
{% set version = "2.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca9fe2cdf97b15ac53ee7bdc7d35a6a2da835fe3b2e4f730c43731a587c2ebce
  patches:
    - 0001-Fixes-for-conda-build-with-Arrow-support.patch

build:
  number: 1
  skip: true  # [py2k]
  script:
    - ENABLE_EXT_MODULES=true {{ PYTHON }} -m pip install . --no-deps -vvv    # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vvv    # [win]
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - pip
    - cython  # [unix]
    - arrow-cpp  # [unix]
    - pyarrow  # [unix]
    - numpy 1.16.*  # [unix]
  run:
    - python
    - azure-common <2.0.0
    - azure-storage-blob <12.0.0
    - boto3 >=1.4.4,<1.12.0
    - botocore >=1.5.0,<1.15.0
    - requests <2.24.0
    - urllib3 >=1.20,<1.26.0
    - certifi <2021.0.0
    - pytz <2021.0
    - pycryptodomex >=3.2,!=3.5.0,<4.0.0
    - pyOpenSSL >=16.2.0,<21.0.0
    - cffi >=1.9,<1.14
    - cryptography >=1.8.2,<3.0.0
    - ijson <3.0.0
    - pyjwt <2.0.0
    - idna <2.10
    - oscrypto <2.0.0
    - asn1crypto >0.24.0,<2.0.0
    - keyring !=16.1.0,<22
    - pyarrow >=0.16.0,<0.17.0
    - pandas >=1,<1.1

test:
  requires:
    - pip
  imports:
    - snowflake
    - snowflake.connector
    - snowflake.connector.arrow_result  # [unix]
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
