{% set name = "snowflake-connector-python" %}
{% set version = "2.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0beba8eb9c1dec2782d52491d058256e1f5d9e010114a80ff3b8e3905be655fd
  patches:
    - 0001-Fixes-for-conda-build-with-Arrow-support.patch  # [not win]

build:
  number: 0
  skip: true  # [py2k]
  script:
    - ENABLE_EXT_MODULES=true {{ PYTHON }} -m pip install . --no-deps -vvv    # [unix]
    - {{ PYTHON }} -m pip install . --no-deps -vvv    # [win]
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - pip
    - cython  # [unix]
    - arrow-cpp  # [unix]
    - pyarrow  # [unix]
    - numpy 1.16.*  # [unix]
  run:
    - python
    - asn1crypto >0.24.0,<2.0.0
    - azure-common <2.0.0
    - azure-storage-blob >=12,<13
    - boto3 >=1.4.4,<1.14.0
    - certifi <2021.0.0
    - cffi >=1.9,<1.14
    - cryptography >=2.5.0,<3.0.0
    - idna <2.10
    - oscrypto <2.0.0
    - pandas >=1,<1.1
    - pyOpenSSL >=16.2.0,<21.0.0
    - pyarrow >=0.17.0,<0.18.0
    - pycryptodomex >=3.2,!=3.5.0,<4.0.0
    - pyjwt <2.0.0
    - pytz <2021.0
    - requests <2.24.0
    - urllib3 >=1.20,<1.26.0

test:
  requires:
    - pip
  imports:
    - snowflake
    - snowflake.connector
    - snowflake.connector.arrow_result  # [unix]
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
