{% set name = "snowflake-connector-python" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2d0f6f0b4ae688ebada9d5ff31b0c7f66643edf607283887c064e4f73fba859

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - azure-common
    - azure-storage-blob
    - boto3 >=1.4.4,<1.10.0
    - botocore >=1.5.0,<1.13.0
    - certifi
    - future
    - six
    - pytz
    - pycryptodomex >=3.2,!=3.5.0
    - pyOpenSSL >=16.2.0
    - cffi >=1.9
    - cryptography >=1.8.2
    - ijson
    - pyjwt
    - idna
    - asn1crypto <1.0.0a0
    - pyasn1 >=0.4.0,<0.5.0  # [py==27]
    - pyasn1-modules >=0.2.0,<0.3.0  # [py==27]
    - enum34  # [py==27]
    - urllib3 >=1.21.1,<1.25  # [py==27]
    - keyring !=16.1.0
    - pyarrow >=0.14.0  # [py3k]

test:
  imports:
    - snowflake
    - snowflake.connector

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Snowflake Connector for Python'
  description: |
    The Snowflake Connector for Python provides an interface for 
    developing Python applications that can connect to Snowflake 
    and perform all standard operations. It provides a programming 
    alternative to developing applications in Java or C/C++ using 
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
