schema_version: 1

context:
  name: snowflake-connector-python
  version: 3.14.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/snowflakedb/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 87de09a6a224f095dc25caf17c40c36d076cfdeca34598b0671b792886ed765e

build:
  number: 0
  python:
    entry_points:
      - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
      - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
      - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
      - snowflake-export-certs = snowflake.connector.tool.export_certs:main
  dynamic_linking:
    rpaths:
      - lib
      - ${{ PREFIX }}/lib
      - if: unix
        then: ${{ SP_DIR }}/pyarrow
      - if: win
        then: ${{ SP_DIR }}\pyarrow

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - packaging
  run:
    - python
    - asn1crypto >0.24.0,<2.0.0
    - boto3 >=1.0
    - botocore >=1.0
    - cffi >=1.9,<2.0.0
    - cryptography >=3.1.0
    - pyOpenSSL >=22.0.0,<26.0.0
    - pyjwt <3.0.0
    - pytz
    - requests <3.0.0
    - packaging
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - if: match(python, "<=3.9")
      then: urllib3 >=1.21.1,<2
    - certifi >=2017.4.17
    - typing_extensions >=4.3,<5
    - filelock >=3.5,<4
    - sortedcontainers >=2.4.0
    - platformdirs >=2.6.0,<5.0.0
    - tomlkit
  run_constraints:
    - pandas >1,<3

tests:
  - python:
      imports:
        - snowflake
        - snowflake.connector
        - snowflake.connector.nanoarrow_arrow_iterator
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  homepage: https://github.com/snowflakedb/snowflake-connector-python
  repository: https://github.com/snowflakedb/snowflake-connector-python
  documentation: https://docs.snowflake.net/manuals/user-guide/python-connector.html

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
