schema_version: 1

context:
  name: snowflake-connector-python
  version: "4.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/snowflakedb/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 673c9ee2e9a6c5b51c1b59d116e00b5b81d0279a65787265242c220c619593be

build:
  number: 0
  python:
    entry_points:
      - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
      - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
      - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.1
    - packaging
  run:
    - python
    - asn1crypto >0.24.0,<2.0.0
    - boto3 >=1.24
    - botocore >=1.24
    - cryptography >=46.0.5
    - pyOpenSSL >=24.0.0
    - pyjwt >=2.10.1,<3.0.0
    - pytz
    - requests >=2.32.4,<3.0.0
    - packaging
    - charset-normalizer >=2,<4
    - idna >=3.7,<4
    - certifi >=2024.7.4
    - typing_extensions >=4.3,<5
    - filelock >=3.5,<4
    - sortedcontainers >=2.4.0
    - platformdirs >=2.6.0,<5.0.0
    - tomlkit
  run_constraints:
    # mirroring upstream [pandas] extra from setup.cfg
    - if: match(python, "<3.13")
      then: pandas >=1.0.0,<3
      else: pandas >=2.1.2,<3
    - if: match(python, "<3.14")
      then: pyarrow >=14.0.1
      else: pyarrow >=14.0.1,<24

tests:
  - python:
      pip_check: true
      imports:
        - snowflake
        - snowflake.connector
        - snowflake.connector.nanoarrow_arrow_iterator

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  homepage: https://github.com/snowflakedb/snowflake-connector-python
  repository: https://github.com/snowflakedb/snowflake-connector-python
  documentation: https://docs.snowflake.net/manuals/user-guide/python-connector.html

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
