schema_version: 1

context:
  name: snowflake-connector-python
  version: "4.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/snowflakedb/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9a03043eb33c7725036d8cc9b8439e1db0a742e7df6afa926379b820608a47f8

build:
  number: 0
  python:
    entry_points:
      - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
      - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
      - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
      - snowflake-export-certs = snowflake.connector.tool.export_certs:main
  dynamic_linking:
    rpaths:
      - lib
      - ${{ PREFIX }}/lib
      - if: unix
        then: ${{ SP_DIR }}/pyarrow
      - if: win
        then: ${{ SP_DIR }}\pyarrow

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - packaging
  run:
    - python
    - asn1crypto >0.24.0,<2.0.0
    - boto3 >=1.24
    - botocore >=1.24
    - cffi >=1.9,<2.0.0
    - cryptography >=44.0.1
    - pyOpenSSL >=24.0.0,<26.0.0
    - pyjwt >=2.10.1,<3.0.0
    - pytz
    - requests >=2.32.4,<3.0.0
    - packaging
    - charset-normalizer >=2,<4
    - idna >=3.7,<4
    - certifi >=2024.7.4
    - typing_extensions >=4.3,<5
    - filelock >=3.5,<4
    - sortedcontainers >=2.4.0
    - platformdirs >=2.6.0,<5.0.0
    - tomlkit
  run_constraints:
    - pandas >=2.1.2,<3

tests:
  - python:
      pip_check: true
      imports:
        - snowflake
        - snowflake.connector
        - snowflake.connector.nanoarrow_arrow_iterator

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  homepage: https://github.com/snowflakedb/snowflake-connector-python
  repository: https://github.com/snowflakedb/snowflake-connector-python
  documentation: https://docs.snowflake.net/manuals/user-guide/python-connector.html

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
