travis:
  secure:
    BINSTAR_TOKEN: bC+jYvxC+ekw97kY5DpNvPPM//ueoep56bws9am+rkHHxBLNZIt9JAFd/5IZwgL8yM4ZozmDrOJe7FPy495v8Duh9PvFdjdR5UvFGuzKxFU39HQk9SaWkq9kScR/MkTAFvlT/2XyqckXK9DBeb8bh1+cTvAQcsuXSjm2PchjzaLNT0euUxmQba8B2XFaObbhLmygcfi0kxiszpUrXA+cZM35b2IU0tyr73dyfRbQ+2unsvWdpT3PTBPx+FXkUS0OcJGjPh4oQP6t42KNKWjtdI0drqKgUx78fiaLOwk8NzejA3bkCScsgR54MXEmux6oIVDENGR1JpLqe4ZJFx1WhqYSJX3PIfwUC7Lx33d5JJBLp1Zk0XkM0+x810vYJ/VLFSE5MWow2SZJY/HxEKzWvgoWOtfVs8DWKVy43sCYiNWjl6hBiifKBYA9qjwSysmhXuL9LlRg8scHu3irGNozhNHI7p2u4VR//HFlc1cgAAJru5LREjYaEppV2dju1+eLWa9fAxrrztyNM8Rola808mzqJ466hjoPU7IdamgQuwoDaLZ+8SY9Pqo3+BjFVFfPy8MQOzdlNAJllvAqfL32+48Cxeij7jx0vH4L1muyD6Fl4O6xYLWJLUy0xx8ozLydaPM0Rgrnrzq5M7NQDnypv+KChYRGZAh62jTHsF5xyGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
