# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      win_64_arrow_cpp6.0.2numpy1.20python3.8.____cpython:
        CONFIG: win_64_arrow_cpp6.0.2numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp6.0.2numpy1.20pytho_h25446e55f1
      win_64_arrow_cpp6.0.2numpy1.20python3.9.____cpython:
        CONFIG: win_64_arrow_cpp6.0.2numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp6.0.2numpy1.20pytho_h2fb4616b31
      win_64_arrow_cpp6.0.2numpy1.21python3.10.____cpython:
        CONFIG: win_64_arrow_cpp6.0.2numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp6.0.2numpy1.21pytho_h77e16da44c
      win_64_arrow_cpp6.0.2numpy1.23python3.11.____cpython:
        CONFIG: win_64_arrow_cpp6.0.2numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp6.0.2numpy1.23pytho_h723db197c1
      win_64_arrow_cpp7.0.1numpy1.20python3.8.____cpython:
        CONFIG: win_64_arrow_cpp7.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp7.0.1numpy1.20pytho_h7430381d3f
      win_64_arrow_cpp7.0.1numpy1.20python3.9.____cpython:
        CONFIG: win_64_arrow_cpp7.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp7.0.1numpy1.20pytho_h6cf3a29358
      win_64_arrow_cpp7.0.1numpy1.21python3.10.____cpython:
        CONFIG: win_64_arrow_cpp7.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp7.0.1numpy1.21pytho_h34f92eb90e
      win_64_arrow_cpp7.0.1numpy1.23python3.11.____cpython:
        CONFIG: win_64_arrow_cpp7.0.1numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp7.0.1numpy1.23pytho_h7d56d8f045
      win_64_arrow_cpp8.0.1numpy1.20python3.8.____cpython:
        CONFIG: win_64_arrow_cpp8.0.1numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp8.0.1numpy1.20pytho_h32935853d8
      win_64_arrow_cpp8.0.1numpy1.20python3.9.____cpython:
        CONFIG: win_64_arrow_cpp8.0.1numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp8.0.1numpy1.20pytho_h611b28312a
      win_64_arrow_cpp8.0.1numpy1.21python3.10.____cpython:
        CONFIG: win_64_arrow_cpp8.0.1numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp8.0.1numpy1.21pytho_h4a6a32a30f
      win_64_arrow_cpp8.0.1numpy1.23python3.11.____cpython:
        CONFIG: win_64_arrow_cpp8.0.1numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp8.0.1numpy1.23pytho_h9bce0c10f3
      win_64_arrow_cpp9.0.0numpy1.20python3.8.____cpython:
        CONFIG: win_64_arrow_cpp9.0.0numpy1.20python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp9.0.0numpy1.20pytho_h858288c92f
      win_64_arrow_cpp9.0.0numpy1.20python3.9.____cpython:
        CONFIG: win_64_arrow_cpp9.0.0numpy1.20python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp9.0.0numpy1.20pytho_hc7357fa2a8
      win_64_arrow_cpp9.0.0numpy1.21python3.10.____cpython:
        CONFIG: win_64_arrow_cpp9.0.0numpy1.21python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp9.0.0numpy1.21pytho_hda58ff2772
      win_64_arrow_cpp9.0.0numpy1.23python3.11.____cpython:
        CONFIG: win_64_arrow_cpp9.0.0numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_arrow_cpp9.0.0numpy1.23pytho_h6edc9f92cc
    maxParallel: 8
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\

  steps:
    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call activate base
        mamba.exe install 'python=3.9' conda-build conda pip boa 'conda-forge-ci-setup=3' -c conda-forge --strict-channel-priority --yes
      displayName: Install conda-build

    - script: set PYTHONUNBUFFERED=1
      displayName: Set PYTHONUNBUFFERED

    # Configure the VM
    - script: |
        call activate base
        setup_conda_rc .\ ".\recipe" .\.ci_support\%CONFIG%.yaml
      displayName: conda-forge CI setup

    # Configure the VM.
    - script: |
        set "CI=azure"
        call activate base
        run_conda_forge_build_setup
      displayName: conda-forge build setup

    - script: |
        call activate base
        if EXIST LICENSE.txt (
          copy LICENSE.txt "recipe\\recipe-scripts-license.txt"
        )
        conda.exe mambabuild "recipe" -m .ci_support\%CONFIG%.yaml --suppress-variables
      displayName: Build recipe
      env:
        PYTHONUNBUFFERED: 1
    - script: |
        set CI=azure
        set CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        set FEEDSTOCK_NAME=$(build.Repository.Name)
        set ARTIFACT_STAGING_DIR=$(Build.ArtifactStagingDirectory)
        set CONDA_BLD_DIR=$(CONDA_BLD_PATH)
        set BLD_ARTIFACT_PREFIX=conda_artifacts
        if "%AGENT_JOBSTATUS%" == "Failed" (
            set ENV_ARTIFACT_PREFIX=conda_envs
        )
        call ".scripts\create_conda_build_artifacts.bat"
      displayName: Prepare conda build artifacts
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Store conda build artifacts
      condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(BLD_ARTIFACT_PATH)
        artifactName: $(BLD_ARTIFACT_NAME)

    - task: PublishPipelineArtifact@1
      displayName: Store conda build environment artifacts
      condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(ENV_ARTIFACT_PATH)
        artifactName: $(ENV_ARTIFACT_NAME)
    - script: |
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        validate_recipe_outputs "%FEEDSTOCK_NAME%"
      displayName: Validate Recipe Outputs

    - script: |
        set "GIT_BRANCH=%BUILD_SOURCEBRANCHNAME%"
        set "FEEDSTOCK_NAME=%BUILD_REPOSITORY_NAME:*/=%"
        call activate base
        upload_package --validate --feedstock-name="%FEEDSTOCK_NAME%" .\ ".\recipe" .ci_support\%CONFIG%.yaml
      displayName: Upload package
      env:
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
      condition: and(succeeded(), not(eq(variables['UPLOAD_PACKAGES'], 'False')), not(eq(variables['Build.Reason'], 'PullRequest')))